Project reactor
Wectro20/KotlinPetProject pull request #11
Opened 2023-09-22 11:10 UTC by Wectro20

2023-09-22 12:43 UTC, ajax-gnatiuk-s commented
@tetty-pa please review

2023-09-22 14:16 UTC, Wectro20 commented
I have problems with saving csv file, trying to fix it as soon as i can

2023-09-23 18:16 UTC, Wectro20 commented
@tetty-pa review pls

2023-09-24 12:05 UTC, ajax-gnatiuk-s requested changes

2023-09-24 12:05 UTC, ajax-gnatiuk-s commented on src/main/kotlin/com/ajax/cryptocurrency/service/CryptocurrencyService.kt
> +        }
Could be simplified
```kotlin
        return Flux.fromIterable(cryptocurrencies)
            .flatMap { name ->
                Mono.zip(
                    cryptocurrencyRepository.findMinMaxByName(name, 1),
                    cryptocurrencyRepository.findMinMaxByName(name, -1)
                ).map {
                    "$name,${it.t1},${it.t1}\n"
                }
            }
            .collectList()
            .map { list ->
                file.bufferedWriter().use { writer ->
                    writer.append("Cryptocurrency Name,Min Price,Max Price\n")
                    list.forEach { writer.append(it) }
                }
                file
            }
```

2023-09-25 07:21 UTC, Wectro20 commented on src/main/kotlin/com/ajax/cryptocurrency/controller/CryptocurrencyController.kt
> +    fun getMaxCryptocurrencyPrice(@RequestParam() name: String): ResponseEntity<Mono<Cryptocurrency>> =
done

2023-09-25 07:22 UTC, Wectro20 commented on src/test/kotlin/com/ajax/cryptocurrency/natscontroller/NatsCryptocurrencyGetMinPriceControllerTest.kt
> +        verify { cryptocurrencyService.findMinMaxPriceByCryptocurrencyName(cryptoName, 1).block() }
done

2023-09-25 07:27 UTC, Wectro20 commented on src/main/kotlin/com/ajax/cryptocurrency/service/CryptocurrencyService.kt
> +        }
thx for hint

2023-09-25 07:29 UTC, Wectro20 commented on src/main/kotlin/com/ajax/cryptocurrency/nats/NatsCryptocurrencyGetMinPriceController.kt
> +        val cryptocurrency = cryptocurrencyService.findMinMaxPriceByCryptocurrencyName(request.name.name, 1).block()!!
I'll change it to your version, I like it better

2023-09-25 07:45 UTC, Wectro20 commented on src/main/kotlin/com/ajax/cryptocurrency/nats/NatsCryptocurrencyGetMinPriceController.kt
> +        val cryptocurrency = cryptocurrencyService.findMinMaxPriceByCryptocurrencyName(request.name.name, 1).block()!!
done

2023-09-25 10:39 UTC, ajax-gnatiuk-s requested changes

2023-09-25 10:39 UTC, ajax-gnatiuk-s commented on src/test/kotlin/com/ajax/cryptocurrency/natscontroller/NatsCryptocurrencyGetAllControllerTest.kt
> +        every { cryptocurrencyService.findAll().collectList().block() } returns cryptocurrencyList
```suggestion
        every { cryptocurrencyService.findAll() } returns Flux.fromIterable(cryptocurrencyList)
```

2023-09-25 10:39 UTC, ajax-gnatiuk-s commented on src/test/kotlin/com/ajax/cryptocurrency/natscontroller/NatsCryptocurrencyGetAllControllerTest.kt
> +        verify { cryptocurrencyService.findAll().collectList().block() }
```suggestion
        verify { cryptocurrencyService.findAll() }
```

2023-09-25 10:52 UTC, Wectro20 commented on src/test/kotlin/com/ajax/cryptocurrency/natscontroller/NatsCryptocurrencyGetAllControllerTest.kt
> +        every { cryptocurrencyService.findAll().collectList().block() } returns cryptocurrencyList
fixed

2023-09-25 10:52 UTC, Wectro20 commented on src/test/kotlin/com/ajax/cryptocurrency/natscontroller/NatsCryptocurrencyGetAllControllerTest.kt
> +        verify { cryptocurrencyService.findAll().collectList().block() }
fixed

2023-09-25 14:03 UTC, tetty-pa approved these changes

2023-09-25 14:23 UTC, merged